[package]
name = "goblin"
version = "5.0.0"
edition = "2018"

[dependencies]
serenity = { version = "0.10.9", features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api"] }
tokio = { version = "1.12.0", features = ["full"] }
serde_json = "1.0.68"
